version: '3'
 
services:
  pg:
    build:
      context: pg
    image: opentileserver/pg:1
    env_file:
      - .env
    volumes:
      - ./vol/pg:/var/lib/postgresql/data
    restart: always
    hostname: pg
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -h pg -U ${POSTGRES_USER}
      interval: 60s
      retries: 2
      timeout: 10s
 
  tile:
    build:
      context: tile
      args:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - PBF_URL=${PBF_URL}
    env_file:
      - .env
    image: opentileserver/tile:1
    volumes:
      - ./vol/tiles:/var/cache/renderd/tiles
    ports:
      - 8080:80
    depends_on:
      - "pg"
    privileged: true
