version: '3'

services:
  pg:
    image: acugis/pg:latest
    env_file:
      - .env
    volumes:
      - ./vol/pg:/var/lib/postgresql/data
    restart: always
    hostname: pg
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -h pg -U ${POSTGRES_USER}
      interval: 60s
      retries: 2
      timeout: 10s

  tile:
    env_file:
      - .env
    image: acugis/opentileserver:latest
    volumes:
      - ./vol/tiles:/var/cache/renderd/tiles
    ports:
      - 8080:80
    depends_on:
      - "pg"
    privileged: true
